apiVersion: v1
kind: ReplicationController
metadata:
  name: sourcegraph
spec:
  replicas: 1
  selector:
    app: sourcegraph
  template:
    metadata:
      labels:
        app: sourcegraph
    spec:
      containers:
      - name: src
        image: sourcegraph/sourcegraph:latest
        volumeMounts:
        - name: data
          mountPath: /etc/sourcegraph
        - name: config
          mountPath: /home/sourcegraph/.sourcegraph
        ports:
        - containerPort: 3080
          protocol: TCP
        - containerPort: 3443
          protocol: TCP 
        - containerPort: 3100
          protocol: TCP 
        imagePullPolicy: Always
      volumes:
      - name: data
        gcePersistentDisk:
          pdName: sourcegraph-data
          fsType: "ext4"
      - name: config
        gcePersistentDisk:
          pdName: sourcegraph-config
          fsType: "ext4"
      restartPolicy: Always
