apiVersion: v1
kind: Service
metadata:
  name: sourcegraph
spec:
  selector:
    app: sourcegraph
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3001
  - name: grpc
    protocol: TCP
    port: 3100
  type: LoadBalancer
